// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tUCfX9Zh3OBDxiSiI95o-HEc34YyTAQ',
    appId: '1:197291034827:web:a1da06023a1534e28d734e',
    messagingSenderId: '197291034827',
    projectId: 'dewaforvaluee',
    authDomain: 'dewaforvaluee.firebaseapp.com',
    databaseURL: 'https://dewaforvaluee-default-rtdb.firebaseio.com',
    storageBucket: 'dewaforvaluee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8QHjMKNAuBA00rgyVeglXyT74pgiWIfI',
    appId: '1:197291034827:android:2a0f93be3d3120e08d734e',
    messagingSenderId: '197291034827',
    projectId: 'dewaforvaluee',
    databaseURL: 'https://dewaforvaluee-default-rtdb.firebaseio.com',
    storageBucket: 'dewaforvaluee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Wvkw4hEEzD40eyp9EsOHSqZHJktBUgs',
    appId: '1:197291034827:ios:b48e77393b81a4f58d734e',
    messagingSenderId: '197291034827',
    projectId: 'dewaforvaluee',
    databaseURL: 'https://dewaforvaluee-default-rtdb.firebaseio.com',
    storageBucket: 'dewaforvaluee.firebasestorage.app',
    iosBundleId: 'com.example.agaproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Wvkw4hEEzD40eyp9EsOHSqZHJktBUgs',
    appId: '1:197291034827:ios:b48e77393b81a4f58d734e',
    messagingSenderId: '197291034827',
    projectId: 'dewaforvaluee',
    databaseURL: 'https://dewaforvaluee-default-rtdb.firebaseio.com',
    storageBucket: 'dewaforvaluee.firebasestorage.app',
    iosBundleId: 'com.example.agaproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-tUCfX9Zh3OBDxiSiI95o-HEc34YyTAQ',
    appId: '1:197291034827:web:275a12813021712f8d734e',
    messagingSenderId: '197291034827',
    projectId: 'dewaforvaluee',
    authDomain: 'dewaforvaluee.firebaseapp.com',
    databaseURL: 'https://dewaforvaluee-default-rtdb.firebaseio.com',
    storageBucket: 'dewaforvaluee.firebasestorage.app',
  );
}
